"""add_finance_wallet_billing_payment_models

Revision ID: 25aa00c1c5c9
Revises: 554c6950560a
Create Date: 2026-07-05 16:50:53.346833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '25aa00c1c5c9'
down_revision: Union[str, None] = '554c6950560a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fin_billing_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False, comment='INVOICE | RECEIPT | REMINDER | PDF'),
    sa.Column('content', sa.Text(), nullable=True, comment='Template body (HTML / Jinja2 / Markdown)'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Whether this template is the default for its type'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_billing_templates')),
    comment='Invoice, receipt, reminder, and PDF templates'
    )
    op.create_index(op.f('ix_fin_billing_templates_created_by'), 'fin_billing_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_fin_billing_templates_deleted_at'), 'fin_billing_templates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fin_billing_templates_updated_by'), 'fin_billing_templates', ['updated_by'], unique=False)
    op.create_table('fin_payment_gateways',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='RAZORPAY | STRIPE | PAYU | CASHFREE | etc.'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Encrypted gateway credentials and configuration'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False, comment='SANDBOX | PRODUCTION'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_payment_gateways')),
    sa.UniqueConstraint('name', name=op.f('uq_fin_payment_gateways_name')),
    comment='Gateway configuration and provider information'
    )
    op.create_index(op.f('ix_fin_payment_gateways_created_by'), 'fin_payment_gateways', ['created_by'], unique=False)
    op.create_index(op.f('ix_fin_payment_gateways_deleted_at'), 'fin_payment_gateways', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fin_payment_gateways_updated_by'), 'fin_payment_gateways', ['updated_by'], unique=False)
    op.create_table('fin_wallets',
    sa.Column('owner_type', sa.String(length=50), nullable=False, comment='STUDENT | ORGANIZATION | EMPLOYEE | INTERNAL'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='UUID of the owning entity (soft FK)'),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False, comment='Current wallet balance'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='ISO 4217 currency code'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='ACTIVE | SUSPENDED | CLOSED'),
    sa.Column('is_frozen', sa.Boolean(), nullable=False, comment='Whether the wallet is currently frozen'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_wallets')),
    comment='Master wallet for students, organizations, employees, and internal accounts'
    )
    op.create_index(op.f('ix_fin_wallets_created_by'), 'fin_wallets', ['created_by'], unique=False)
    op.create_index(op.f('ix_fin_wallets_deleted_at'), 'fin_wallets', ['deleted_at'], unique=False)
    op.create_index('ix_fin_wallets_owner', 'fin_wallets', ['owner_type', 'owner_id'], unique=True)
    op.create_index(op.f('ix_fin_wallets_owner_id'), 'fin_wallets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_fin_wallets_updated_by'), 'fin_wallets', ['updated_by'], unique=False)
    op.create_table('fin_wallet_adjustments',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=50), nullable=False, comment='CREDIT | DEBIT'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='UUID of the approving user (soft FK)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['wallet_id'], ['fin_wallets.id'], name=op.f('fk_fin_wallet_adjustments_wallet_id_fin_wallets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_wallet_adjustments')),
    comment='Manual financial adjustments performed by Finance team'
    )
    op.create_index(op.f('ix_fin_wallet_adjustments_approved_by'), 'fin_wallet_adjustments', ['approved_by'], unique=False)
    op.create_index(op.f('ix_fin_wallet_adjustments_created_by'), 'fin_wallet_adjustments', ['created_by'], unique=False)
    op.create_index(op.f('ix_fin_wallet_adjustments_deleted_at'), 'fin_wallet_adjustments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fin_wallet_adjustments_updated_by'), 'fin_wallet_adjustments', ['updated_by'], unique=False)
    op.create_index(op.f('ix_fin_wallet_adjustments_wallet_id'), 'fin_wallet_adjustments', ['wallet_id'], unique=False)
    op.create_table('fin_wallet_audit_logs',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False, comment='Machine-readable action tag, e.g. WALLET_CREATED, BALANCE_CREDITED'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured payload with before/after snapshots'),
    sa.Column('performed_by', sa.UUID(), nullable=True, comment='UUID of the acting user (soft FK)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address (IPv4 or IPv6)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['wallet_id'], ['fin_wallets.id'], name=op.f('fk_fin_wallet_audit_logs_wallet_id_fin_wallets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_wallet_audit_logs')),
    comment='Immutable audit trail for all wallet operations'
    )
    op.create_index('ix_fin_wallet_audit_created', 'fin_wallet_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_fin_wallet_audit_logs_created_by'), 'fin_wallet_audit_logs', ['created_by'], unique=False)
    op.create_index(op.f('ix_fin_wallet_audit_logs_deleted_at'), 'fin_wallet_audit_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fin_wallet_audit_logs_performed_by'), 'fin_wallet_audit_logs', ['performed_by'], unique=False)
    op.create_index(op.f('ix_fin_wallet_audit_logs_updated_by'), 'fin_wallet_audit_logs', ['updated_by'], unique=False)
    op.create_index(op.f('ix_fin_wallet_audit_logs_wallet_id'), 'fin_wallet_audit_logs', ['wallet_id'], unique=False)
    op.create_table('fin_wallet_freeze_history',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False, comment='FREEZE | UNFREEZE'),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True, comment='UUID of the user who performed the action (soft FK)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['wallet_id'], ['fin_wallets.id'], name=op.f('fk_fin_wallet_freeze_history_wallet_id_fin_wallets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_wallet_freeze_history')),
    comment='Freeze / unfreeze history for wallets'
    )
    op.create_index(op.f('ix_fin_wallet_freeze_history_created_by'), 'fin_wallet_freeze_history', ['created_by'], unique=False)
    op.create_index(op.f('ix_fin_wallet_freeze_history_deleted_at'), 'fin_wallet_freeze_history', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fin_wallet_freeze_history_performed_by'), 'fin_wallet_freeze_history', ['performed_by'], unique=False)
    op.create_index(op.f('ix_fin_wallet_freeze_history_updated_by'), 'fin_wallet_freeze_history', ['updated_by'], unique=False)
    op.create_index(op.f('ix_fin_wallet_freeze_history_wallet_id'), 'fin_wallet_freeze_history', ['wallet_id'], unique=False)
    op.create_table('fin_wallet_limits',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('max_balance', sa.Numeric(precision=15, scale=2), nullable=True, comment='Maximum allowed wallet balance'),
    sa.Column('daily_debit_limit', sa.Numeric(precision=15, scale=2), nullable=True, comment='Maximum debit allowed per day'),
    sa.Column('daily_credit_limit', sa.Numeric(precision=15, scale=2), nullable=True, comment='Maximum credit allowed per day'),
    sa.Column('overdraft_allowed', sa.Boolean(), nullable=False),
    sa.Column('overdraft_limit', sa.Numeric(precision=15, scale=2), nullable=True, comment='Maximum overdraft amount if allowed'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['wallet_id'], ['fin_wallets.id'], name=op.f('fk_fin_wallet_limits_wallet_id_fin_wallets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_wallet_limits')),
    comment='Wallet limits, overdraft settings, and balance constraints'
    )
    op.create_index(op.f('ix_fin_wallet_limits_created_by'), 'fin_wallet_limits', ['created_by'], unique=False)
    op.create_index(op.f('ix_fin_wallet_limits_deleted_at'), 'fin_wallet_limits', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fin_wallet_limits_updated_by'), 'fin_wallet_limits', ['updated_by'], unique=False)
    op.create_index(op.f('ix_fin_wallet_limits_wallet_id'), 'fin_wallet_limits', ['wallet_id'], unique=True)
    op.create_table('fin_wallet_refunds',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_transaction_id', sa.UUID(), nullable=True, comment='Original transaction that is being refunded (soft FK)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='PENDING | COMPLETED | FAILED'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['wallet_id'], ['fin_wallets.id'], name=op.f('fk_fin_wallet_refunds_wallet_id_fin_wallets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_wallet_refunds')),
    comment='Refunds credited back into wallets'
    )
    op.create_index(op.f('ix_fin_wallet_refunds_created_by'), 'fin_wallet_refunds', ['created_by'], unique=False)
    op.create_index(op.f('ix_fin_wallet_refunds_deleted_at'), 'fin_wallet_refunds', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fin_wallet_refunds_source_transaction_id'), 'fin_wallet_refunds', ['source_transaction_id'], unique=False)
    op.create_index(op.f('ix_fin_wallet_refunds_updated_by'), 'fin_wallet_refunds', ['updated_by'], unique=False)
    op.create_index(op.f('ix_fin_wallet_refunds_wallet_id'), 'fin_wallet_refunds', ['wallet_id'], unique=False)
    op.create_table('fin_wallet_transactions',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False, comment='CREDIT | DEBIT | TRANSFER | REFUND | SCHOLARSHIP | INCENTIVE | CASHBACK | ADJUSTMENT'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=100), nullable=True, comment='Entity type that triggered this transaction (e.g. INVOICE, REFUND_REQUEST)'),
    sa.Column('reference_id', sa.UUID(), nullable=True, comment='UUID of the triggering entity (soft FK)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['wallet_id'], ['fin_wallets.id'], name=op.f('fk_fin_wallet_transactions_wallet_id_fin_wallets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_wallet_transactions')),
    comment='All wallet credits, debits, transfers, refunds, scholarships, incentives, cashback, and adjustments'
    )
    op.create_index(op.f('ix_fin_wallet_transactions_created_by'), 'fin_wallet_transactions', ['created_by'], unique=False)
    op.create_index(op.f('ix_fin_wallet_transactions_deleted_at'), 'fin_wallet_transactions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fin_wallet_transactions_reference_id'), 'fin_wallet_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_fin_wallet_transactions_updated_by'), 'fin_wallet_transactions', ['updated_by'], unique=False)
    op.create_index(op.f('ix_fin_wallet_transactions_wallet_id'), 'fin_wallet_transactions', ['wallet_id'], unique=False)
    op.create_index('ix_fin_wallet_txn_created', 'fin_wallet_transactions', ['created_at'], unique=False)
    op.create_index('ix_fin_wallet_txn_type', 'fin_wallet_transactions', ['transaction_type'], unique=False)
    op.create_table('fin_invoice_reminders',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False, comment='UPCOMING_DUE | DUE_TODAY | OVERDUE | FAILED_PAYMENT'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the reminder was actually sent'),
    sa.Column('channel', sa.String(length=50), nullable=False, comment='EMAIL | SMS | WHATSAPP'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='PENDING | SENT | FAILED'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['invoice_id'], ['fin_invoices.id'], name=op.f('fk_fin_invoice_reminders_invoice_id_fin_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_invoice_reminders')),
    comment='Reminder history for due invoices'
    )
    op.create_index(op.f('ix_fin_invoice_reminders_created_by'), 'fin_invoice_reminders', ['created_by'], unique=False)
    op.create_index(op.f('ix_fin_invoice_reminders_deleted_at'), 'fin_invoice_reminders', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fin_invoice_reminders_invoice_id'), 'fin_invoice_reminders', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_fin_invoice_reminders_updated_by'), 'fin_invoice_reminders', ['updated_by'], unique=False)
    op.create_table('fin_refund_requests',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True, comment='UUID of the user who raised the request (soft FK)'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='PENDING | APPROVED | REJECTED'),
    sa.Column('reviewed_by', sa.UUID(), nullable=True, comment='UUID of the reviewer (soft FK)'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['invoice_id'], ['fin_invoices.id'], name=op.f('fk_fin_refund_requests_invoice_id_fin_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_refund_requests')),
    comment='Refund requests awaiting approval'
    )
    op.create_index(op.f('ix_fin_refund_requests_created_by'), 'fin_refund_requests', ['created_by'], unique=False)
    op.create_index(op.f('ix_fin_refund_requests_deleted_at'), 'fin_refund_requests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fin_refund_requests_invoice_id'), 'fin_refund_requests', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_fin_refund_requests_requested_by'), 'fin_refund_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_fin_refund_requests_reviewed_by'), 'fin_refund_requests', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_fin_refund_requests_updated_by'), 'fin_refund_requests', ['updated_by'], unique=False)
    op.create_table('fin_payment_gateway_logs',
    sa.Column('payment_transaction_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='ORDER_CREATED | PAYMENT_AUTHORIZED | PAYMENT_CAPTURED | WEBHOOK_RECEIVED | etc.'),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('webhook_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False, comment='Whether this log entry has been reconciled'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['fin_payment_transactions.id'], name=op.f('fk_fin_payment_gateway_logs_payment_transaction_id_fin_payment_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_payment_gateway_logs')),
    comment='Gateway request/response logs, verification data, webhook payloads, and reconciliation info'
    )
    op.create_index(op.f('ix_fin_payment_gateway_logs_created_by'), 'fin_payment_gateway_logs', ['created_by'], unique=False)
    op.create_index(op.f('ix_fin_payment_gateway_logs_deleted_at'), 'fin_payment_gateway_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fin_payment_gateway_logs_payment_transaction_id'), 'fin_payment_gateway_logs', ['payment_transaction_id'], unique=False)
    op.create_index(op.f('ix_fin_payment_gateway_logs_updated_by'), 'fin_payment_gateway_logs', ['updated_by'], unique=False)
    op.create_index('ix_fin_pg_log_created', 'fin_payment_gateway_logs', ['created_at'], unique=False)
    op.create_index('ix_fin_pg_log_event_type', 'fin_payment_gateway_logs', ['event_type'], unique=False)
    op.create_table('fin_payment_logs',
    sa.Column('payment_transaction_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False, comment='INITIATED | AUTHORIZED | CAPTURED | FAILED | REFUNDED | DISPUTED | SETTLED | etc.'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured event payload'),
    sa.Column('performed_by', sa.UUID(), nullable=True, comment='UUID of the acting user or system (soft FK)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['fin_payment_transactions.id'], name=op.f('fk_fin_payment_logs_payment_transaction_id_fin_payment_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_payment_logs')),
    comment='Complete payment lifecycle and audit events'
    )
    op.create_index('ix_fin_payment_log_created', 'fin_payment_logs', ['created_at'], unique=False)
    op.create_index('ix_fin_payment_log_event', 'fin_payment_logs', ['event'], unique=False)
    op.create_index(op.f('ix_fin_payment_logs_created_by'), 'fin_payment_logs', ['created_by'], unique=False)
    op.create_index(op.f('ix_fin_payment_logs_deleted_at'), 'fin_payment_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fin_payment_logs_payment_transaction_id'), 'fin_payment_logs', ['payment_transaction_id'], unique=False)
    op.create_index(op.f('ix_fin_payment_logs_performed_by'), 'fin_payment_logs', ['performed_by'], unique=False)
    op.create_index(op.f('ix_fin_payment_logs_updated_by'), 'fin_payment_logs', ['updated_by'], unique=False)
    op.create_table('fin_payment_reconciliations',
    sa.Column('payment_transaction_id', sa.UUID(), nullable=False),
    sa.Column('erp_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='Amount recorded in the ERP'),
    sa.Column('gateway_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Amount reported by the payment gateway'),
    sa.Column('bank_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Amount confirmed by the bank statement'),
    sa.Column('match_status', sa.String(length=50), nullable=False, comment='MATCHED | MISMATCHED | PENDING'),
    sa.Column('reconciled_by', sa.UUID(), nullable=True, comment='UUID of the user who performed reconciliation (soft FK)'),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discrepancy_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['fin_payment_transactions.id'], name=op.f('fk_fin_payment_reconciliations_payment_transaction_id_fin_payment_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_payment_reconciliations')),
    comment='ERP vs Gateway vs Bank reconciliation records'
    )
    op.create_index(op.f('ix_fin_payment_reconciliations_created_by'), 'fin_payment_reconciliations', ['created_by'], unique=False)
    op.create_index(op.f('ix_fin_payment_reconciliations_deleted_at'), 'fin_payment_reconciliations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fin_payment_reconciliations_payment_transaction_id'), 'fin_payment_reconciliations', ['payment_transaction_id'], unique=False)
    op.create_index(op.f('ix_fin_payment_reconciliations_reconciled_by'), 'fin_payment_reconciliations', ['reconciled_by'], unique=False)
    op.create_index(op.f('ix_fin_payment_reconciliations_updated_by'), 'fin_payment_reconciliations', ['updated_by'], unique=False)
    op.create_table('fin_refund_transactions',
    sa.Column('refund_request_id', sa.UUID(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('refund_method', sa.String(length=50), nullable=False, comment='WALLET | BANK_TRANSFER | GATEWAY_REVERSAL | etc.'),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True, comment='External reference from payment gateway or bank'),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the refund was processed'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['refund_request_id'], ['fin_refund_requests.id'], name=op.f('fk_fin_refund_transactions_refund_request_id_fin_refund_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_refund_transactions')),
    comment='Completed refund transactions'
    )
    op.create_index(op.f('ix_fin_refund_transactions_created_by'), 'fin_refund_transactions', ['created_by'], unique=False)
    op.create_index(op.f('ix_fin_refund_transactions_deleted_at'), 'fin_refund_transactions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fin_refund_transactions_refund_request_id'), 'fin_refund_transactions', ['refund_request_id'], unique=True)
    op.create_index(op.f('ix_fin_refund_transactions_transaction_reference'), 'fin_refund_transactions', ['transaction_reference'], unique=False)
    op.create_index(op.f('ix_fin_refund_transactions_updated_by'), 'fin_refund_transactions', ['updated_by'], unique=False)
    op.drop_column('acad_batches', 'batch_status')
    op.drop_column('acad_batches', 'internship_type')
    op.drop_column('acad_batches', 'metadata')
    op.drop_column('acad_programs', 'max_capacity')
    op.drop_constraint(op.f('intern_opportunities_program_id_fkey'), 'intern_opportunities', type_='foreignkey')
    op.drop_column('intern_opportunities', 'program_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intern_opportunities', sa.Column('program_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('intern_opportunities_program_id_fkey'), 'intern_opportunities', 'acad_programs', ['program_id'], ['id'], ondelete='SET NULL')
    op.add_column('acad_programs', sa.Column('max_capacity', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False))
    op.add_column('acad_batches', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('acad_batches', sa.Column('internship_type', sa.VARCHAR(length=100), server_default=sa.text("'Paid Internship'::character varying"), autoincrement=False, nullable=False))
    op.add_column('acad_batches', sa.Column('batch_status', sa.VARCHAR(length=50), server_default=sa.text("'Draft'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_fin_refund_transactions_updated_by'), table_name='fin_refund_transactions')
    op.drop_index(op.f('ix_fin_refund_transactions_transaction_reference'), table_name='fin_refund_transactions')
    op.drop_index(op.f('ix_fin_refund_transactions_refund_request_id'), table_name='fin_refund_transactions')
    op.drop_index(op.f('ix_fin_refund_transactions_deleted_at'), table_name='fin_refund_transactions')
    op.drop_index(op.f('ix_fin_refund_transactions_created_by'), table_name='fin_refund_transactions')
    op.drop_table('fin_refund_transactions')
    op.drop_index(op.f('ix_fin_payment_reconciliations_updated_by'), table_name='fin_payment_reconciliations')
    op.drop_index(op.f('ix_fin_payment_reconciliations_reconciled_by'), table_name='fin_payment_reconciliations')
    op.drop_index(op.f('ix_fin_payment_reconciliations_payment_transaction_id'), table_name='fin_payment_reconciliations')
    op.drop_index(op.f('ix_fin_payment_reconciliations_deleted_at'), table_name='fin_payment_reconciliations')
    op.drop_index(op.f('ix_fin_payment_reconciliations_created_by'), table_name='fin_payment_reconciliations')
    op.drop_table('fin_payment_reconciliations')
    op.drop_index(op.f('ix_fin_payment_logs_updated_by'), table_name='fin_payment_logs')
    op.drop_index(op.f('ix_fin_payment_logs_performed_by'), table_name='fin_payment_logs')
    op.drop_index(op.f('ix_fin_payment_logs_payment_transaction_id'), table_name='fin_payment_logs')
    op.drop_index(op.f('ix_fin_payment_logs_deleted_at'), table_name='fin_payment_logs')
    op.drop_index(op.f('ix_fin_payment_logs_created_by'), table_name='fin_payment_logs')
    op.drop_index('ix_fin_payment_log_event', table_name='fin_payment_logs')
    op.drop_index('ix_fin_payment_log_created', table_name='fin_payment_logs')
    op.drop_table('fin_payment_logs')
    op.drop_index('ix_fin_pg_log_event_type', table_name='fin_payment_gateway_logs')
    op.drop_index('ix_fin_pg_log_created', table_name='fin_payment_gateway_logs')
    op.drop_index(op.f('ix_fin_payment_gateway_logs_updated_by'), table_name='fin_payment_gateway_logs')
    op.drop_index(op.f('ix_fin_payment_gateway_logs_payment_transaction_id'), table_name='fin_payment_gateway_logs')
    op.drop_index(op.f('ix_fin_payment_gateway_logs_deleted_at'), table_name='fin_payment_gateway_logs')
    op.drop_index(op.f('ix_fin_payment_gateway_logs_created_by'), table_name='fin_payment_gateway_logs')
    op.drop_table('fin_payment_gateway_logs')
    op.drop_index(op.f('ix_fin_refund_requests_updated_by'), table_name='fin_refund_requests')
    op.drop_index(op.f('ix_fin_refund_requests_reviewed_by'), table_name='fin_refund_requests')
    op.drop_index(op.f('ix_fin_refund_requests_requested_by'), table_name='fin_refund_requests')
    op.drop_index(op.f('ix_fin_refund_requests_invoice_id'), table_name='fin_refund_requests')
    op.drop_index(op.f('ix_fin_refund_requests_deleted_at'), table_name='fin_refund_requests')
    op.drop_index(op.f('ix_fin_refund_requests_created_by'), table_name='fin_refund_requests')
    op.drop_table('fin_refund_requests')
    op.drop_index(op.f('ix_fin_invoice_reminders_updated_by'), table_name='fin_invoice_reminders')
    op.drop_index(op.f('ix_fin_invoice_reminders_invoice_id'), table_name='fin_invoice_reminders')
    op.drop_index(op.f('ix_fin_invoice_reminders_deleted_at'), table_name='fin_invoice_reminders')
    op.drop_index(op.f('ix_fin_invoice_reminders_created_by'), table_name='fin_invoice_reminders')
    op.drop_table('fin_invoice_reminders')
    op.drop_index('ix_fin_wallet_txn_type', table_name='fin_wallet_transactions')
    op.drop_index('ix_fin_wallet_txn_created', table_name='fin_wallet_transactions')
    op.drop_index(op.f('ix_fin_wallet_transactions_wallet_id'), table_name='fin_wallet_transactions')
    op.drop_index(op.f('ix_fin_wallet_transactions_updated_by'), table_name='fin_wallet_transactions')
    op.drop_index(op.f('ix_fin_wallet_transactions_reference_id'), table_name='fin_wallet_transactions')
    op.drop_index(op.f('ix_fin_wallet_transactions_deleted_at'), table_name='fin_wallet_transactions')
    op.drop_index(op.f('ix_fin_wallet_transactions_created_by'), table_name='fin_wallet_transactions')
    op.drop_table('fin_wallet_transactions')
    op.drop_index(op.f('ix_fin_wallet_refunds_wallet_id'), table_name='fin_wallet_refunds')
    op.drop_index(op.f('ix_fin_wallet_refunds_updated_by'), table_name='fin_wallet_refunds')
    op.drop_index(op.f('ix_fin_wallet_refunds_source_transaction_id'), table_name='fin_wallet_refunds')
    op.drop_index(op.f('ix_fin_wallet_refunds_deleted_at'), table_name='fin_wallet_refunds')
    op.drop_index(op.f('ix_fin_wallet_refunds_created_by'), table_name='fin_wallet_refunds')
    op.drop_table('fin_wallet_refunds')
    op.drop_index(op.f('ix_fin_wallet_limits_wallet_id'), table_name='fin_wallet_limits')
    op.drop_index(op.f('ix_fin_wallet_limits_updated_by'), table_name='fin_wallet_limits')
    op.drop_index(op.f('ix_fin_wallet_limits_deleted_at'), table_name='fin_wallet_limits')
    op.drop_index(op.f('ix_fin_wallet_limits_created_by'), table_name='fin_wallet_limits')
    op.drop_table('fin_wallet_limits')
    op.drop_index(op.f('ix_fin_wallet_freeze_history_wallet_id'), table_name='fin_wallet_freeze_history')
    op.drop_index(op.f('ix_fin_wallet_freeze_history_updated_by'), table_name='fin_wallet_freeze_history')
    op.drop_index(op.f('ix_fin_wallet_freeze_history_performed_by'), table_name='fin_wallet_freeze_history')
    op.drop_index(op.f('ix_fin_wallet_freeze_history_deleted_at'), table_name='fin_wallet_freeze_history')
    op.drop_index(op.f('ix_fin_wallet_freeze_history_created_by'), table_name='fin_wallet_freeze_history')
    op.drop_table('fin_wallet_freeze_history')
    op.drop_index(op.f('ix_fin_wallet_audit_logs_wallet_id'), table_name='fin_wallet_audit_logs')
    op.drop_index(op.f('ix_fin_wallet_audit_logs_updated_by'), table_name='fin_wallet_audit_logs')
    op.drop_index(op.f('ix_fin_wallet_audit_logs_performed_by'), table_name='fin_wallet_audit_logs')
    op.drop_index(op.f('ix_fin_wallet_audit_logs_deleted_at'), table_name='fin_wallet_audit_logs')
    op.drop_index(op.f('ix_fin_wallet_audit_logs_created_by'), table_name='fin_wallet_audit_logs')
    op.drop_index('ix_fin_wallet_audit_created', table_name='fin_wallet_audit_logs')
    op.drop_table('fin_wallet_audit_logs')
    op.drop_index(op.f('ix_fin_wallet_adjustments_wallet_id'), table_name='fin_wallet_adjustments')
    op.drop_index(op.f('ix_fin_wallet_adjustments_updated_by'), table_name='fin_wallet_adjustments')
    op.drop_index(op.f('ix_fin_wallet_adjustments_deleted_at'), table_name='fin_wallet_adjustments')
    op.drop_index(op.f('ix_fin_wallet_adjustments_created_by'), table_name='fin_wallet_adjustments')
    op.drop_index(op.f('ix_fin_wallet_adjustments_approved_by'), table_name='fin_wallet_adjustments')
    op.drop_table('fin_wallet_adjustments')
    op.drop_index(op.f('ix_fin_wallets_updated_by'), table_name='fin_wallets')
    op.drop_index(op.f('ix_fin_wallets_owner_id'), table_name='fin_wallets')
    op.drop_index('ix_fin_wallets_owner', table_name='fin_wallets')
    op.drop_index(op.f('ix_fin_wallets_deleted_at'), table_name='fin_wallets')
    op.drop_index(op.f('ix_fin_wallets_created_by'), table_name='fin_wallets')
    op.drop_table('fin_wallets')
    op.drop_index(op.f('ix_fin_payment_gateways_updated_by'), table_name='fin_payment_gateways')
    op.drop_index(op.f('ix_fin_payment_gateways_deleted_at'), table_name='fin_payment_gateways')
    op.drop_index(op.f('ix_fin_payment_gateways_created_by'), table_name='fin_payment_gateways')
    op.drop_table('fin_payment_gateways')
    op.drop_index(op.f('ix_fin_billing_templates_updated_by'), table_name='fin_billing_templates')
    op.drop_index(op.f('ix_fin_billing_templates_deleted_at'), table_name='fin_billing_templates')
    op.drop_index(op.f('ix_fin_billing_templates_created_by'), table_name='fin_billing_templates')
    op.drop_table('fin_billing_templates')
    # ### end Alembic commands ###
